Repository milieuinfo/webcomponent-vl-ui-modal, pull requests merged in 2019-10, with the labels that each got.

#59 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
Labels: maintenance

#64 #63 focus probleem opgelost
  demo/vl-modal-test.js
  demo/vl-modal.html
  dist/modal.js
  package-lock.json
  package.json
Labels: bug

#66 #65 not-auto-closable attribuut toegevoegd
  demo/vl-modal.html
  test/vl-modal.test.html
  vl-modal.src.js
Labels: enhancement

#68 Update README.md
  README.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
Labels: maintenance

#69 Update README.md
  README.md
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
Labels: maintenance
