Repository milieuinfo/webcomponent-vl-ui-modal, pull requests merged in 2019-09, with the labels that each got.

#22 UIG-218
  vl-modal.src.js
Labels: maintenance

#23 Update link naar demo
  vl-modal.src.js
Labels: maintenance

#28 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#10 Update dependency sinon to v7.4.1
  package-lock.json
  package.json
Labels: dependencies, renovate

#9 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#35 Update dependency vl-ui-icon to v2.0.11
  package-lock.json
  package.json
Labels: dependencies

#34 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#33 Update dependency vl-ui-button to v1.1.9
  package-lock.json
Labels: dependencies

#32 Update dependency sinon to v7.4.2
  package-lock.json
  package.json
Labels: dependencies

#31 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#30 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#29 Update dependency @govflanders/vl-ui-modal to v3.9.0
  package-lock.json
Labels: dependencies

#37 Update dependency vl-ui-action-group to v1.0.17
  package-lock.json
  package.json
Labels: dependencies

#36 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#38 Update dependency vl-ui-core to v1.4.7
  package-lock.json
  package.json
Labels: dependencies

#45 Automatic commit via update script
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
Labels: maintenance

#47 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
Labels: maintenance

#55 Update dependency sinon to v7.5.0
  package-lock.json
  package.json
Labels: dependencies

#54 Update vl-ui-util
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
Labels: maintenance
