Repository milieuinfo/webcomponent-vl-ui-modal, pull requests merged in 2020-02, with the labels that each got.

#97 Introductie allow-overflow attribuut
  demo/vl-modal.html
  package-lock.json
  package.json
  src/style.scss
  src/vl-modal.src.js
  style.css
  test/e2e/components/vl-modal.js
  test/e2e/modal.test.js
  test/e2e/pages/vl-modal.page.js
  test/unit/vl-modal.test.html
Labels: enhancement

#100 Absoluut import pad probleem bij de vl-ui-webcomponenten demo
  demo/vl-modal-test.js
Labels: bug

#101 Stijl import vervangen door inhoud, probleem met absolute paden
  package-lock.json
  package.json
  src/vl-modal.src.js
  vl-modal.min.js
  vl-modal.src.js
Labels: bug

#104 Fix return await
  package-lock.json
  package.json
  test/e2e/modal.test.js
  test/e2e/pages/vl-modal.page.js
Labels: bugfix

#105 Update datepicker naar latest
  package-lock.json
  package.json
Labels: chore

#106 Update util zodat de docker-compose de shared memory settings overneemt
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore

#107 Gebruik de datepicker in de modal
  .gitignore
  package-lock.json
  package.json
  test/e2e/components/vl-modal.js
  test/e2e/modal.test.js
  test/e2e/pages/vl-modal-auto-open.page.js
Labels: chore

#110 Nieuwe structuur en build scripts implementatie vervangen door vl-ui-util build implementatie
  CODEOWNERS
  bamboo-specs/bamboo.yml
  demo/vl-modal-auto-open.html
  demo/vl-modal-test.js
  demo/vl-modal.html
  docker-compose-release.yml
  lib/modal.js
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/vl-modal.js
  test/docker-compose.yml
  test/unit/vl-modal.test.html
Labels: chore
