Repository milieuinfo/webcomponent-vl-ui-modal, pull requests merged in 2020-01, with the labels that each got.

#85 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  package-lock.json
  package.json
Labels: maintenance

#87 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#86 Overbodig NPM release import scripts verwijderd
  package.json
  style.css
  vl-modal.js
Labels: maintenance

#88 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#89 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#91 #90: Fix positionering van de <dialog> polyfill
  demo/demo.css
  demo/demo.css.map
  style.css
  vl-modal.js
  vl-modal.src.js
Labels: bug
