Repository milieuinfo/webcomponent-vl-ui-modal, pull requests merged in 2020-06, with the labels that each got.

#133 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-modal.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/vl-modal.js
  test/e2e/components/vl-modal.js
  test/e2e/modal.test.js
  test/e2e/pages/vl-modal-auto-open.page.js
  test/e2e/pages/vl-modal.page.js
  test/unit/vl-modal.test.html
Labels: chore

#134 Importeer sinon vanuit node_modules voor de unit testen
  demo/vl-modal-auto-open.html
  demo/vl-modal-test.js
  demo/vl-modal.html
  package-lock.json
  test/e2e/modal.test.js
  test/unit/vl-modal.test.html
Labels: bugfix

#137 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
  test/e2e/pages/vl-modal.page.js
Labels: bug

#139 Deduplicatie NPM run scripts
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
