Repository milieuinfo/webcomponent-vl-ui-modal, pull requests merged in 2020-04, with the labels that each got.

#118 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#123 Modal zonder closable attribuut mag niet gesloten worden in Firefox a.d.h.v. escape toets
  lib/modal.js
  package-lock.json
  package.json
  test/e2e/modal.test.js
Labels: bug

#126 Oplossing voor verkeerd aria-hidden gebruik
  lib/modal.js
Labels: bug

#127 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#128 Update dependency @govflanders/vl-ui-util to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#119 Update dependency vl-ui-button to v5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#120 Update dependency vl-ui-icon to v5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#129 Update dependencies
  package-lock.json
  package.json
Labels: chore
